### ISSUE TITLE
UX/DX discussion: Check out possibility to have dev tools in separate window (by default)

### ISSUE THREAD

**Issue by adnasa** [DextApp/dext#38]
I already found it mildly frustrating to _try to_ inspect the application through webkit's devtools

I think you can see why 😜 
![dev-tools](https://cloud.githubusercontent.com/assets/462507/18230471/96c1b596-729c-11e6-9ba5-8e72b88a3716.jpg)

This also affects my train of thought when checking through the state 

**with results**
![good height](https://cloud.githubusercontent.com/assets/462507/18230510/b3179bba-729d-11e6-9e81-be6d97df2919.jpg)

**without results**
![without results](https://cloud.githubusercontent.com/assets/462507/18230512/bcf5ac76-729d-11e6-8549-d52baa3c2060.jpg)

We should check out the possibility to:
- have dev tools open (by default) on a separate window
- when <kbd>dext</kbd> is on dev mode; it is open _at all times_ (even if this requires a configured flag on the electron-build)

**Comment by vutran** [comment]
This is one of the frustrations I have during the development as well but I kept putting it off. I knew it would be caught by someone else 😂

I'm for this option as it would greatly enhance the DX.

**Comment by adnasa** [comment]
I haven't considered deeply how we manage this, tbh.
since the app is only an <kbd>input</kbd> field 😖 

one option (might be a bad, but we're going to have to try) is that when it is in dev mode, not only is it open at all times, but the app consists of the input + list (even) in window of a specific size, then at least it'll make it a bit easier...

we're going to have to sleep on this and look around of inspiration

**Comment by Magellol** [comment]
I'm up to keep this discussion open and eventually try something. I've caught myself making some modifications to app/main/index.js and stash them to be able to re-use each time I'm debugging the app.

<img width="1188" alt="screen shot 2017-01-23 at 8 58 56 pm" src="https://cloud.githubusercontent.com/assets/3819093/22230998/d7d6db48-e1ae-11e6-950a-6fb525e24af9.png">

Personally though my dev tools are separated from the input as you can see [here](https://cl.ly/2N071h1Y2g40) but I'm facing the same issue for Redux dev tools being completely crushed by the window's height.

Coming up with a good solution will definitely speed up the development 💯

**Comment by vutran** [comment]
@Magellol I definitely feel the pain points of this during the initial development of Dext and this may have a huge role in gaining new contributors. My initial thought is to perhaps enclose the entire app into a container that acts like a regular browser and override the window hooks (like you have above) to toggle the inner container instead of the window itself.

I may take a look at this later in the week/weekend unless you want to have a stab at it?

<pre>
-----------------------------
|  this is the search bar    |
|----------------------------|
</pre>

to:

<pre>
------------------------------------------------
|                                              |
|           -----------------------------      |
|           | this is the search bar     |     |
|           |----------------------------|     |
|                                              |
-----------------------------------------------
</pre>

**Comment by Magellol** [comment]
@vutran Yeah that'd be interesting to do! I can check it out during this week :)

**Comment by adnasa** [comment]
[on a side note](http://asciiflow.com/): I love your drawing @vutran

**Comment by vutran** [comment]
@Magellol Looks like you're on the right track. We'll probably want to disable [transparencies](https://github.com/vutran/dext/blob/f311912013294ecccc9cbc49ae697c66ba391d0d/app/main/index.js#L324) as well in dev mode.

**Comment by Magellol** [comment]
Awesome. I have a few ideas. Ideally I'd like to avoid throwing `env === 'development'` everywhere, so I'm thinking about a solution that'd load a browser window or another with some other params based on the env. That'd be way easier to change config later if needed.

👍

**Comment by Magellol** [comment]
Just a little update. I'm still planning to tackle this, I have some demo code running. Although, I'm a little busier than usual that's why I couldn't do much these days but I will get to it for sure 👍 .

**Comment by vutran** [comment]
@Magellol No worries. Take all the time you need. 😄

**Comment by Magellol** [comment]
Hey guys. So I was able to allow some time to work on this issue but I think I'm heading into a rabbit hole and I will never get out.

I went with the idea of creating window factories (production and development in this case) and in which you'd define every piece of window behaviour you want such as:

```javascript
module.exports = function windowFactory(theme) {
  let windowInstance = null;

  function createWindow(options) {
    const allOptions = Object.assign({}, options, {
      backgroundColor: (theme && theme.window.backgroundColor) ? theme.window.backgroundColor : '#FFF',
    });

    return new BrowserWindow(allOptions);
  }

  return {
    getDefaultOptions() {
      return {
        width: WINDOW_DEFAULT_WIDTH,
        height: WINDOW_DEFAULT_HEIGHT,
        maxHeight: WINDOW_MAX_HEIGHT,
        center: false,
        frame: false,
        show: false,
        minimizable: false,
        maximizable: false,
        hasShadow: true,
        skipTaskbar: true,
        transparent: true,
      };
    },
    getInstance(options = {}) {
      windowInstance = windowInstance || createWindow(options);
      return windowInstance;
    },
  };
};
```

With this method, we could create subsequent windows and make them inherit from the production one if necessary. All that went well but I'm having a lot of troubles migrating some logic from `main/index.js` to these factories because in `index` it's using a global `win` variable pretty much everywhere.

So I was wondering if:

a) If you guys dig this factory idea.
b) If so, I think before doing any of it we should refactor a bit `main/index.js` to allow using local window variables first somehow then it'll get easier to move these logic to factories.

**Comment by adnasa** [comment]
What is the status of this now?
cc @vutran @Magellol

**Comment by vutran** [comment]
@adnasa `dext` itself has been pretty inactive. Since the development of [`omnibar`](https://github.com/vutran/omnibar), I may think of doing a rewrite to utilize `omnibar` as the underlying search component for `dext` in the future.
